In [2]:
print("Hello Jupyter")

Hello Jupyter


In [4]:
import numpy as np
np.array([(1,2.5,4), (12,24,36)], dtype = float)

array([[ 1. ,  2.5,  4. ],
       [12. , 24. , 36. ]])

In [5]:
s = np.arange(8).reshape(2,4)
for x in s:
    print(x)

[0 1 2 3]
[4 5 6 7]


In [6]:
a = np.array([1.0, 2.0, 3.0])
b = 3.0
a * b

array([3., 6., 9.])